#!/usr/bin/env bash
#
# Per-task isolated sandboxes for parallel development.
#
# `new` gives a task its own git worktree (separate directory + branch), its own
# Python virtualenv, and its own Postgres container on a free port. Several tasks
# can therefore run the database-backed tests at the same time without colliding.
#
# Isolation comes from two things: `uv` puts a .venv in each worktree
# automatically, and each sandbox gets its own Docker Compose *project name*, so
# its containers and its pgdata volume are separate from every sibling's.
#
# Run database commands inside a worktree via `scripts/db.sh` (it loads the
# sandbox's port + project name). Plain `uv run ...` needs no wrapper.
#
# Usage:
#   scripts/worktree.sh new <slug>     create branch task/<slug> + sandbox
#   scripts/worktree.sh ls             list active sandboxes (+ db ports)
#   scripts/worktree.sh rm  <slug>     stop db, remove worktree, delete branch
#
# Worktrees are siblings of the main clone, under <parent>/scout-wt/<slug>, on
# the Linux-native filesystem. See docs/DEVELOPMENT.md § "Parallel development".

set -euo pipefail

die() { printf 'error: %s\n' "$*" >&2; exit 1; }

usage() { sed -n '3,22p' "$0" | sed 's/^# \{0,1\}//'; exit "${1:-0}"; }

main_worktree() { git worktree list --porcelain | sed -n 's/^worktree //p' | head -1; }

valid_slug() {
  [[ "$1" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]] || die "invalid slug '$1' (letters, digits, . _ -)"
}

# True if a PR for branch $1 has already been merged. Squash/rebase merges rewrite
# the commits, so `git branch -d` still sees the branch as "unmerged" — this
# catches that. Needs `gh`; without it returns false so the caller keeps the safe
# error.
branch_merged_via_pr() {
  command -v gh >/dev/null 2>&1 || return 1
  local n
  n=$(gh pr list --head "$1" --state merged --json number --jq 'length' 2>/dev/null) || return 1
  [[ "${n:-0}" -gt 0 ]]
}

free_port() {
  python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1",0)); print(s.getsockname()[1]); s.close()'
}

cmd_new() {
  local slug="${1:-}"
  [[ -n "$slug" ]] || usage 1
  valid_slug "$slug"

  local branch="task/$slug" base_dir wt_dir
  base_dir="$(dirname "$(main_worktree)")"
  wt_dir="$base_dir/scout-wt/$slug"

  git show-ref --verify --quiet "refs/heads/$branch" && die "branch $branch already exists"
  [[ -e "$wt_dir" ]] && die "$wt_dir already exists"

  git fetch --quiet origin 2>/dev/null || echo "note: could not fetch origin; basing on local main"
  local base="main"
  git show-ref --verify --quiet refs/remotes/origin/main && base="origin/main"

  # `git worktree add` briefly locks refs; retry so concurrent `new` calls survive.
  local tries=0
  until git worktree add -b "$branch" "$wt_dir" "$base" 2>/tmp/wt-add.$$; do
    tries=$((tries + 1))
    if [[ $tries -ge 5 ]]; then
      cat /tmp/wt-add.$$ >&2
      rm -f /tmp/wt-add.$$
      die "git worktree add failed"
    fi
    sleep 0.5
  done
  rm -f /tmp/wt-add.$$

  local port project
  port="$(free_port)"
  project="scout-$slug"

  # Loaded by scripts/db.sh. Kept separate from .env because this is shell syntax
  # while .env is Scout's own dotenv-format settings file.
  mkdir -p "$wt_dir/.sandbox"
  {
    echo "# Auto-generated by scripts/worktree.sh — this sandbox's isolated Postgres."
    echo "# Not committed; removed with the worktree."
    echo "export SCOUT_DB_PORT=\"$port\""
    echo "export COMPOSE_PROJECT_NAME=\"$project\""
    echo "export SCOUT_DATABASE_URL=\"postgresql://scout:scout@localhost:$port/scout\""
  } > "$wt_dir/.sandbox/env"

  # Scout reads .env for its own settings; seed it so `uv run scout ...` inside
  # the worktree talks to THIS sandbox's database, and defaults to the fake LLM
  # backend so a parallel task cannot quietly spend money.
  {
    echo "# Auto-generated by scripts/worktree.sh for this sandbox."
    echo "SCOUT_DATABASE_URL=postgresql://scout:scout@localhost:$port/scout"
    echo "SCOUT_DB_PORT=$port"
    echo "SCOUT_LLM_BACKEND=fake"
  } > "$wt_dir/.env"

  # The git-ignored local docs live only in the main clone, so a fresh worktree
  # would not have them. Symlink them in so the worker can read its card, and so
  # the task board stays one shared source of truth. These names are git-ignored,
  # so the symlinks never get committed.
  local main_clone doc
  main_clone="$(main_worktree)"
  for doc in tasks CLAUDE.md; do
    if [[ -e "$main_clone/$doc" && ! -e "$wt_dir/$doc" ]]; then
      ln -s "$main_clone/$doc" "$wt_dir/$doc"
    fi
  done

  echo
  echo "created sandbox:"
  echo "  worktree:   $wt_dir"
  echo "  branch:     $branch  (off $base)"
  echo "  postgres:   localhost:$port  (compose project '$project')"
  echo "  local docs: tasks/ CLAUDE.md (symlinked from the main clone)"
  echo
  echo "next:"
  echo "  cd $wt_dir"
  echo "  uv sync                       # this worktree's own .venv"
  echo "  scripts/db.sh up              # this sandbox's own Postgres"
  echo "  uv run pytest -m 'not integration'"
}

cmd_ls() {
  echo "Active worktrees:"
  git worktree list
  echo
  echo "Task branches + isolated Postgres (last commit age; flagged if no worktree):"
  local b slug age wt base_dir flag port
  base_dir="$(dirname "$(main_worktree)")"
  while read -r b; do
    slug="${b#task/}"
    age=$(git log -1 --format='%cr' "$b" 2>/dev/null || echo '?')
    wt="$base_dir/scout-wt/$slug"
    flag=""
    [[ -d "$wt" ]] || flag="  [!] no worktree (stale?)"
    port="?"
    if [[ -f "$wt/.sandbox/env" ]]; then
      port=$(sed -n 's/^export SCOUT_DB_PORT="\(.*\)"$/\1/p' "$wt/.sandbox/env")
    fi
    printf '  %-32s db :%-6s %s%s\n' "$b" "$port" "$age" "$flag"
  done < <(git for-each-ref --format='%(refname:short)' refs/heads/task/)
}

cmd_rm() {
  local slug="${1:-}"
  [[ -n "$slug" ]] || usage 1
  valid_slug "$slug"
  local branch="task/$slug" base_dir wt_dir
  base_dir="$(dirname "$(main_worktree)")"
  wt_dir="$base_dir/scout-wt/$slug"

  # -v drops the pgdata volume too; leaving it behind quietly eats disk.
  if [[ -f "$wt_dir/.sandbox/env" ]]; then
    (
      set +u
      . "$wt_dir/.sandbox/env"
      cd "$wt_dir" && docker compose down -v --remove-orphans
    ) >/dev/null 2>&1 || true
    echo "stopped sandbox Postgres and removed its volume"
  fi

  if [[ -d "$wt_dir" ]]; then
    # Drop the doc symlinks first so they neither block removal nor get followed.
    find "$wt_dir" -maxdepth 1 -type l -delete 2>/dev/null || true
    git worktree remove "$wt_dir" \
      || die "worktree has uncommitted changes; commit/push or: git worktree remove --force '$wt_dir'"
    echo "removed worktree: $wt_dir"
  else
    git worktree prune
  fi

  if git show-ref --verify --quiet "refs/heads/$branch"; then
    if git branch -d "$branch" 2>/dev/null; then
      echo "deleted branch:   $branch"
    elif branch_merged_via_pr "$branch"; then
      # Squash/rebase-merged: the work is on main even though `git branch -d`
      # cannot tell.
      git branch -D "$branch"
      echo "deleted branch:   $branch  (squash/rebase-merged via PR)"
    else
      die "branch $branch isn't merged (no merged PR found); if intentional: git branch -D '$branch'"
    fi
  fi
}

[[ $# -ge 1 ]] || usage 1
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || die "not inside a git repository"

sub="$1"
shift
case "$sub" in
  new) cmd_new "$@" ;;
  ls | list) cmd_ls "$@" ;;
  rm | remove) cmd_rm "$@" ;;
  -h | --help | help) usage 0 ;;
  *) die "unknown command '$sub' (try: new | ls | rm)" ;;
esac
